### ISSUE TITLE
Enhance to compatibility with ruby-end.el

### ISSUE THREAD

**Issue by Pitometsu** [ainame/smart-newline.el#18]
It's a feature request.
```
def foo|  RET   def foo
..        --->    |
end             end
```

**Comment by ainame** [comment]
@Pitometsu Thanks comment.

Well.., do you intend this behavior?

```rb
def|  SPACE     def |  foo      def foo|  RET   def foo
      --->             --->              --->    |
                end             end             end
```

I have faced following behavior with ruby-mode.el and ruby-end.el in my environement.
```rb
def|  SPACE     def |  foo      def foo|  RET   def foo
      --->             --->              --->    |
                end             end             
                                                end
```


I use `smartparens.el` in completion of `end` keyword, and it works fine for me.
I recommend it for you, and you can see my configuration in https://github.com/ainame/emacs-d/blob/master/src/el-get-packages-conf/init-smartparens.el

**Comment by Pitometsu** [comment]
Thanks! I use `el-get` too. But don't use *evil-mode*. Is `<evil-ret>` part of *eliv-mode*? So should I use something like `<rebind RET>` instead?

**Comment by Pitometsu** [comment]
Well, I try your setup. It's customized (or outdated?) [smartparens-ruby.el](https://github.com/Fuco1/smartparens/blob/master/smartparens-ruby.el), right?
```patch
***
! (sp-with-modes '(ruby-mode motion-mode)

! (sp-with-modes '(ruby-mode enh-ruby-mode)
***
!                  :unless '(sp-ruby-in-string-word-or-inline-p sp-in-comment-p)
!                  :actions '(insert navigate)

!                  :unless '(sp-ruby-in-string-word-or-inline-p)
!                  :actions '(insert)
***
-                  :actions '(insert)
***
```
So wouldn't you want to create PR for *smarparens* for this if it right enhancement?

In my case with your setup it do not automatically insert `end` after I type `def`, so I should firstly press RET to use *yasnippet*. But this's less magic, your `smart-newline` awesome because it's magic, and user shouldn't think about RET, it jut work...

How you do this step for your setup (without ruby-end?):
```ruby
def|  SPACE   def |  foo
      --->
end           end
```
And should I make another one issue for *ruby-end.el*, perhaps?

**Comment by Pitometsu** [comment]
@ainame Could you suggest me here, please?

**Comment by Pitometsu** [comment]
Oh, sorry, I missed `(require 'smartparens-ruby)`. That's ok now, thank you, @ainame for suggestion and awesome plugin.
